apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  init.sql: |
    CREATE DATABASE fibonacci;

    \c fibonacci

    CREATE TABLE fibonacci (
      id SERIAL PRIMARY KEY,
      index INTEGER UNIQUE,
      value BIGINT
    );
